=== lorypelli/cpkgs/schemas/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "language": {
            "type": "string",
            "enum": [
                "C",
                "C++"
            ]
        },
        "compiler": {
            "type": "string"
        },
        "file_name": {
            "type": "string"
        },
        "include": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "C": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "C++": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "H": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "H++": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "H"
            ]
        },
        "additional_cpp_options": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "extensions": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "code": {
                            "type": "string",
                            "enum": [
                                ".c++",
                                ".cc",
                                ".cp",
                                ".cpp",
                                ".cxx"
                            ]
                        },
                        "header": {
                            "type": "string",
                            "enum": [
                                ".h++",
                                ".hh",
                                ".hp",
                                ".hpp",
                                ".hxx"
                            ]
                        }
                    },
                    "required": [
                        "code",
                        "header"
                    ]
                }
            },
            "required": [
                "extensions"
            ]
        }
    },
    "required": [
        "language",
        "file_name",
        "include"
    ],
    "if": {
        "properties": {
            "language": {
                "const": "C++"
            }
        }
    },
    "then": {
        "required": [
            "additional_cpp_options"
        ]
    },
    "else": {
        "not": {
            "required": [
                "additional_cpp_options"
            ]
        }
    },
    "dependencies": {
        "language": {
            "oneOf": [
                {
                    "properties": {
                        "language": {
                            "const": "C"
                        },
                        "include": {
                            "properties": {
                                "C": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "required": [
                                "C"
                            ],
                            "not": {
                                "required": [
                                    "C++"
                                ]
                            }
                        }
                    }
                },
                {
                    "properties": {
                        "language": {
                            "const": "C++"
                        },
                        "include": {
                            "properties": {
                                "C++": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "required": [
                                "C++"
                            ],
                            "not": {
                                "required": [
                                    "C"
                                ]
                            }
                        }
                    }
                }
            ]
        }
    }
}

=== lorypelli/cpkgs/examples/C/cpkgs.json
{
  "$schema": "https://raw.githubusercontent.com/lorypelli/cpkgs/main/schemas/schema.json",
  "language": "C",
  "compiler": "gcc",
  "file_name": "out",
  "include": {
    "C": [
      "https://raw.githubusercontent.com/lorypelli/input_function/master/input.c"
    ],
    "C++": [],
    "H": [
      "https://raw.githubusercontent.com/lorypelli/input_function/master/input.h"
    ],
    "H++": []
  }
}
